### ISSUE TITLE
Create PLMNT Issuance Service that receives RDDL on Liquid

### ISSUE THREAD

**Issue by GR3G0RYO** [planetmint/PRPs#28]
- [x] Planetmint Message to notarize minting request of a certain amount of PLMNT to and planetmint address: amount, address
- [x] Configure message keeper to only allow this type of message from a preregistered account/address. This address is part of the genesis and has to be maintained by the module genesis state, which can be updated via governance
- [x] The service listing to liquid and notarizing message on planetmint has to be initialised by planetmint/liquid keypairs.
